### ISSUE TITLE
sudo apt-vim init installed everything in /root

### ISSUE THREAD

**Issue by caseydentinger** [egalpin/apt-vim#39]
I do not have always_set_home in sudoers so I think it might be a problem with the script.  I am on Debian Stretch and Python 2.7.11+

**Comment by egalpin** [comment]
Good catch. I should be able to quite easily determine which user is is calling `sudo` and install for that user. Thanks!

**Comment by egalpin** [comment]
@caseydentinger In thinking about this further, I'm wondering what the best solution is.  It's possible that someone would want to install as root; I don't feel I should stop someone from doing so. `sudo -E` could be used if it was desirable to install `apt-vim` for a given user while providing super user privileges.

Would love to get your input!

**Comment by caseydentinger** [comment]
@egalpin what if you did this in the heredoc instead of using the module
which expands to /root (I think because of sudo python?):

HOME = "${HOME}"

I might be missing something...

**Comment by egalpin** [comment]
I think the root of this problem is actually a mistake (my mistake) in the manual installation doc.  I've updated it [here](https://github.com/egalpin/apt-vim/blob/master/README.md#option-2---manual) to reflect the fact that `sudo` is not actually required for the whole installation, but rather just the copying of the `apt-vim` script to `/usr/local/bin`.  I've also updated [install.sh](https://github.com/egalpin/apt-vim/blob/master/install.sh#L40) to include a `-E` flag for `sudo`.

Would you care to give it a whirl?  I can run it in a VM, but would love to know if this fixes the specific issue you're seeing

**Comment by caseydentinger** [comment]
What about setting PATH to include ~/.vimpkg/bin?  Would that eliminate
needing sudo at all?  I believe adding it to .profile would be reasonably
portable.

**Comment by egalpin** [comment]
I like this idea a lot.  Any time you can install software without super user privileges, it's a win.  Just spinning up a VM to test out some changes.  Thanks for the feedback

**Comment by egalpin** [comment]
@caseydentinger Please see #40 :-) 

The only use of `sudo` now is in dependency installation (i.e. installing vim and git). These can be opted out of by a user.

**Comment by caseydentinger** [comment]
Much nicer!  Glad I could help!

**Comment by egalpin** [comment]
Thanks a bunch for your input, closing this issue off :-)
